# Generated by Django 3.0.9 on 2021-05-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_private_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='private_status',
            new_name='public_status',
        ),
    ]
