# Generated by Django 3.0.9 on 2021-05-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210511_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='public_status',
            new_name='private_status',
        ),
    ]
